# This is a Help Document that explains to the user what the investment program does:
print("----------------------------------------------------------------")
print("Welcome to The Long-Term Investment Calculator")
print("----------------------------------------------------------------")
print("Here is a quick overview of the program:")
print("----------------------------------------------------------------")
print("1. The Investment Calculator Gathers Information from the Investor")
print("------------------------------------------------------------------")
print("2. Using the data the calculator calculates based on your investment information provided")
print("-----------------------------------------------------------------------------------------")
print("what the Potential Future Value of your Investment could be in the future.")
print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
print("3. In Addition, the Calculator also uses this information and the history of the global markets to calculate alternative Future Values of your Investment")
print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
print("based on the number of years you invest for your potential return")
print("---------------------------------------------------------------------------------------------------------------------------------------------------------")